FROM php:8.2-apache

# Install system dependencies
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    && docker-php-ext-install pdo pdo_mysql mysqli

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Enable Apache mod_rewrite (optional)
RUN a2enmod rewrite

# env passthroughs
RUN echo "PassEnv PEPPER" >> /etc/apache2/apache2.conf \
 && echo "PassEnv JWT_SECRET" >> /etc/apache2/apache2.conf\
 && echo "PassEnv MYSQL_DATABASE" >> /etc/apache2/apache2.conf \
 && echo "PassEnv MYSQL_PASSWORD" >> /etc/apache2/apache2.conf \
 && echo "PassEnv MYSQL_USER" >> /etc/apache2/apache2.conf \